[package]
cairo-version = "2.5.4"
description = "Replicating Solver contracts for Haiko protocol"
name = "haiko_solver_replicating"
version = "1.0.0"
edition = "2023_11"

[dependencies]
starknet = "2.5.4"
# Imported locally for now, as it is not yet public. Note amm repo needs to be set to same
# version as this repo to build properly
haiko_amm = { git = "https://github.com/haiko-xyz/amm.git" }
haiko_lib = { git = "https://github.com/haiko-xyz/library.git" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.19.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
  'haiko_amm::contracts::market_manager::MarketManager',
  'haiko_lib::mocks::erc20::ERC20'
]

[[tool.snforge.fork]]
name = "MAINNET"
url = 'https://free-rpc.nethermind.io/mainnet-juno'
block_id.tag = "Latest"