[lib]

[package]
name = "haiko_solver_core"
version = "1.0.0"
description = "Core library for Haiko solvers"
edition = "2023_11"

[dependencies]
starknet = "2.6.3"
haiko_lib = { git = "https://github.com/haiko-xyz/library.git", branch = "v2.0.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.21.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.11.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "cairo-v2.6.0" }

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
  'haiko_lib::mocks::erc20::ERC20'
]

[[tool.snforge.fork]]
name = "MAINNET"
url = 'https://free-rpc.nethermind.io/mainnet-juno'
block_id.tag = "Latest"